=== Paulentin/labsUniversity/br4/TypeEnheritance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.example.org/TypeEnheritance"
	xmlns:tns="http://www.example.org/TypeEnheritance" 
	elementFormDefault="qualified">

	<complexType name="Base">
		<sequence>
			<element name="name" type="string" />
			<element name="type" type="string" />
		</sequence>
	</complexType>

	<complexType name="Child">
		<complexContent>
			<extension base="tns:Base">
				<sequence>
					<element name="description" type="string" />
				</sequence>
			</extension>
		</complexContent>

	</complexType>

	<element name="root">
		<complexType>
			<sequence>
				<element name="base" type="tns:Base" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
</schema>

=== Paulentin/labsUniversity/br4/TypeEnheritance.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://www.example.org/TypeEnheritance" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/TypeEnheritance TypeEnheritance.xsd ">
  <tns:base xsi:type="tns:Base">
    <tns:name>tns:name</tns:name>
    <tns:type>tns:type</tns:type>
  </tns:base>
  <tns:base xsi:type="tns:Child">
    <tns:name>tns:name</tns:name>
    <tns:type>tns:type</tns:type>
    <tns:description>tns:description></tns:description>
  </tns:base>
</tns:root>
